version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "000930"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: masterdb
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      #- ./init-scripts:/docker-entrypoint-initdb.d  # 초기화 스크립트 연결
    networks:
      - game-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p000930"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    ports:
      - "6389:6379"
    networks:
      - game-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  gameserver:
    build:
      context: ./server/GameServer
      dockerfile: Dockerfile
    ports:
      - "5105:8080"
    depends_on:
      - mysql
      - redis
    environment:
      ConnectionStrings__MysqlGameDBConnection: "Server=mysql;Database=gamedb;User=root;Password=000930;"
      ConnectionStrings__MasterDBConnection: "Server=mysql;Database=masterdb;User=root;Password=000930;"
      ConnectionStrings__RedisGameDBConnection: "redis:6379"
    networks:
      - game-network

  hiveserver:
    build:
      context: ./server/HiveServer
      dockerfile: Dockerfile
    ports:
      - "5284:8080"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__MysqlHiveDBConnection: "Server=mysql;Database=hivedb;User=root;Password=000930;"
    networks:
      - game-network

  matchserver:
    build:
      context: ./server/MatchServer
      dockerfile: Dockerfile
    ports:
      - "5259:8080"
    depends_on:
      - redis
    environment:
      ConnectionStrings__RedisGameDBConnection: "redis:6379"
    networks:
      - game-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일을 마운트
    ports:
      - "9090:9090"  # Prometheus 웹 UI 포트
    networks:
      - game-network
    depends_on:
      - gameserver
      - hiveserver
      - matchserver
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana 웹 UI 포트
    depends_on:
      - prometheus
    networks:
      - game-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Admin 패스워드 설정 (옵션)
    volumes:
      - grafana-data:/var/lib/grafana

#  nodeexporter:
#    image: prom/node-exporter
#    ports:
#      - "9100:9100"  # Node Exporter 포트
#    networks:
#      - game-network


networks:
  game-network:
    external: true

volumes:
  mysql-data:
  grafana-data:  